# Task - 01

In [36]:
import pandas as pd
dataframe = pd.read_csv("hourly_weather_10_days.csv")
dataframe.head()

,timestamp,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km
0,2023-03-01 00:00:00,16.6,74.4,5.7,1012.5,9.5
1,2023-03-01 01:00:00,16.2,78.5,5.0,1012.1,10.3
2,2023-03-01 02:00:00,15.3,73.3,4.7,NaN,11.1
3,2023-03-01 03:00:00,15.8,72.4,1.3,1005.0,8.9
4,2023-03-01 04:00:00,20.9,70.6,6.8,1016.3,9.8


# Task - 02

In [37]:
dataframe.describe()

,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km
count,228.000000,224.000000,226.000000,223.000000,228.000000
mean,21.315789,66.795982,10.105310,1011.884753,9.989474
std,3.421237,8.190300,3.940668,5.187080,1.022166
min,11.500000,47.800000,1.300000,998.100000,6.800000
25%,18.700000,61.075000,6.625000,1008.900000,9.275000
50%,21.900000,66.300000,9.800000,1012.100000,10.000000
75%,23.925000,72.725000,13.500000,1015.100000,10.700000
max,28.700000,88.100000,17.800000,1027.000000,12.600000


In [38]:
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   timestamp        240 non-null    str    
 1   temperature_C    228 non-null    float64
 2   humidity_%       224 non-null    float64
 3   wind_speed_kmph  226 non-null    float64
 4   pressure_hPa     223 non-null    float64
 5   visibility_km    228 non-null    float64
dtypes: float64(5), str(1)
memory usage: 11.4 KB


In [39]:
df_shape=dataframe.shape
print(f"data frame rows: {df_shape[0]} \ndata frame columns {df_shape[1]}")

data frame rows: 240 
data frame columns 6


In [40]:
print(f" Number of null values in each column:\n {dataframe.isnull().sum()}")

 Number of null values in each column:
 timestamp           0
temperature_C      12
humidity_%         16
wind_speed_kmph    14
pressure_hPa       17
visibility_km      12
dtype: int64


# Task - 03

### fill with zeros

In [41]:
#Handle missing values
df_fill_with_zero = dataframe.fillna(0)
df_fill_with_zero.isnull().sum()


timestamp          0
temperature_C      0
humidity_%         0
wind_speed_kmph    0
pressure_hPa       0
visibility_km      0
dtype: int64

### fill individual columns with mean

#### temprature_C is best with mean and 
#### timestamp is best with forward fill

In [44]:
df_fill_with_mean = dataframe
df_columns = dataframe.columns
df_fill_with_mean[df_columns[1]] = df_fill_with_mean[df_columns[1]].fillna(df_fill_with_mean[df_columns[1]].mean())   
print(df_columns)
print(df_fill_with_mean.isnull().sum())


Index(['timestamp', 'temperature_C', 'humidity_%', 'wind_speed_kmph',
       'pressure_hPa', 'visibility_km'],
      dtype='str')
timestamp           0
temperature_C       0
humidity_%         16
wind_speed_kmph    14
pressure_hPa       17
visibility_km      12
dtype: int64


#### mean of every column

In [60]:
df_columns = dataframe.select_dtypes(exclude = ["string"]).columns # exclude string column
for col in  df_columns:
        print(f"{col}: {dataframe[col].mean()}")


temperature_C: 21.31578947368421
humidity_%: 66.79598214285714
wind_speed_kmph: 10.105309734513275
pressure_hPa: 1011.8847533632287
visibility_km: 9.989473684210529


# Task - 04

### Data Analysis

In [86]:
dataframe["timestamp"]=pd.to_datetime(dataframe["timestamp"])
print(dataframe["timestamp"].dtype)
dataframe["hour"]=dataframe["timestamp"].dt.hour# adding new column name-> hour
humidity_by_hour=dataframe.groupby("hour")["humidity_%"].mean().tail() #grouping data w.r.t to "hour" and selecting "humidity_%" calculation mean of humidity for every hour group
print(humidity_by_hour)

datetime64[us]
hour
19    69.190000
20    67.488889
21    72.700000
22    73.750000
23    79.100000
Name: humidity_%, dtype: float64


# Task - 05

### Reshape matrix

In [125]:
import numpy as np
temp, wind = df_fill_with_mean["temperature_C"].to_numpy(), df_fill_with_mean["wind_speed_kmph"].to_numpy() #changing this into numpy matrix
temp=temp.reshape(10,24)

array([15.9       , 15.7       , 17.6       , 20.        , 22.        ,
       21.2       , 22.7       , 21.5       , 23.6       , 28.7       ,
       20.5       , 25.1       , 22.1       , 24.5       , 22.6       ,
       21.9       , 23.9       , 21.31578947, 24.2       , 22.        ,
       19.9       , 18.8       , 16.5       , 18.        ])

In [159]:
def find_mean(temp):
    return np.round(np.mean(temp, axis=1),2) # axis =1 for rows

def find_max(temp):
    return np.round(np.max(temp, axis=1),2)

def find_min(temp):
    return np.round(np.min(temp, axis=1),2)

In [160]:
mean, mmax, min = find_mean(temp), find_max(temp), find_min(temp)
print(f"mean: {mean}, \nmax: {mmax}, \nmin: {mean}")


mean: [21.26 21.26 21.3  21.43 21.53 21.86 21.18 20.95 20.79 21.6 ], 
max: [28.2 28.7 25.7 27.1 24.9 26.2 25.9 26.  27.1 28.5], 
min: [21.26 21.26 21.3  21.43 21.53 21.86 21.18 20.95 20.79 21.6 ]


### Normalize

In [177]:
def normalize(mat):
    return (mat-mat.mean())/np.std(mat)

normalize(temp)


array([[-1.4173072 , -1.53752522, -1.80801577, -1.65774325, -0.12496347,
        -0.15501798,  0.44607213,  0.35590862, -0.03479995,  2.06901543,
         0.        ,  1.28759828,  1.22748927,  0.62639917,  1.88868839,
         0.74661719,  0.20563609,  0.71656268,  0.53623565,  0.2356906 ,
        -0.93643512, -0.57578105, -0.48561753, -1.98834281],
       [-1.62768874, -1.68779775, -1.11676215, -0.39545402,  0.20563609,
        -0.03479995,  0.41601763,  0.05536356,  0.68650818,  2.21928795,
        -0.24518149,  1.13732576,  0.2356906 ,  0.95699873,  0.38596312,
         0.17558158,  0.77667169,  0.        ,  0.86683521,  0.20563609,
        -0.42550852, -0.75610808, -1.44736171, -0.99654413],
       [-2.31894237, -1.68779775, -0.8462716 , -1.62768874,  1.31765279,
        -0.12496347, -0.15501798, -0.18507248,  0.29579961,  1.31765279,
         1.04716224, -0.03479995,  1.25754378,  0.17558158,  0.32585411,
         1.01710774,  0.92694422,  0.        ,  0.59634466,  0.92694422,
  

### filter with mask

In [178]:
mask = wind > 15
high_wind = wind[mask]
high_wind

array([17.6, 16. , 16.5, 16.3, 16.7, 15.8, 17.8, 15.1, 16.3, 15.2, 17. ,
       15.9, 15.6, 15.8, 15.4, 15.6, 16.3, 15.3, 16.2, 16.9, 15.3, 15.2,
       15.5, 17.4, 17.4, 15.4, 15.4, 16.5, 17. , 15.7])

# Task - 06

In [179]:
def daily_summary(mat): 
    return {"mean": find_mean(mat), "max": find_max(mat), "min": find_min(mat) }
daily_summary(temp)

{'mean': array([21.26, 21.26, 21.3 , 21.43, 21.53, 21.86, 21.18, 20.95, 20.79,
        21.6 ]),
 'max': array([28.2, 28.7, 25.7, 27.1, 24.9, 26.2, 25.9, 26. , 27.1, 28.5]),
 'min': array([14.7, 15.7, 13.6, 15.9, 12.4, 15.5, 15.3, 13.5, 14.3, 11.5])}